# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-31 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_resource_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='col_int_01',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='col_json_01',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_debug',
            field=models.IntegerField(default=0),
        ),
    ]
