# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180724_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
