# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('type', models.IntegerField()),
                ('process_type', models.IntegerField()),
                ('value', models.TextField()),
                ('pid', models.IntegerField()),
                ('next_id', models.IntegerField()),
                ('pre_id', models.IntegerField()),
                ('is_leaf', models.IntegerField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
